spring:
  datasource:
    url: jdbc:postgresql://192.168.10.133:5432/postgres
    username: postgres
    password: '0000'
    driver-class-name: org.postgresql.Driver
  
server:
  port: 8060

mybatis:
  type-aliases-package: com.example.*
  configuration:
    map-underscore-to-camel-case: true
  
  